// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBND8Dz0BbZ7hGoJjkvfYa9AJfRGisGboQ',
    appId: '1:398628925673:web:b22486e0be90e847700078',
    messagingSenderId: '398628925673',
    projectId: 'vitalai-ceb5c',
    authDomain: 'vitalai-ceb5c.firebaseapp.com',
    storageBucket: 'vitalai-ceb5c.firebasestorage.app',
    measurementId: 'G-9QRJR9ZFQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCljNh-rJEw8b7xrl4XY7btvVR4JBYEdQw',
    appId: '1:398628925673:android:f1ad9b6e35c545fb700078',
    messagingSenderId: '398628925673',
    projectId: 'vitalai-ceb5c',
    storageBucket: 'vitalai-ceb5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcgo2voZefwQ5HrQA08YDb6ldj30gs14I',
    appId: '1:398628925673:ios:7b8ca4b3eafa5a0a700078',
    messagingSenderId: '398628925673',
    projectId: 'vitalai-ceb5c',
    storageBucket: 'vitalai-ceb5c.firebasestorage.app',
    iosBundleId: 'com.example.miPrimerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcgo2voZefwQ5HrQA08YDb6ldj30gs14I',
    appId: '1:398628925673:ios:7b8ca4b3eafa5a0a700078',
    messagingSenderId: '398628925673',
    projectId: 'vitalai-ceb5c',
    storageBucket: 'vitalai-ceb5c.firebasestorage.app',
    iosBundleId: 'com.example.miPrimerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBND8Dz0BbZ7hGoJjkvfYa9AJfRGisGboQ',
    appId: '1:398628925673:web:4d2cd9d46fd1ffdd700078',
    messagingSenderId: '398628925673',
    projectId: 'vitalai-ceb5c',
    authDomain: 'vitalai-ceb5c.firebaseapp.com',
    storageBucket: 'vitalai-ceb5c.firebasestorage.app',
    measurementId: 'G-TRR2GDTMZT',
  );
}